2018-12-07 18:06:03,680 ERROR: Exception on /auth/login [POST] [in /home/leewel/.local/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/leewel/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/leewel/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/leewel/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/leewel/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/leewel/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/leewel/Development/repos/Blog/app/auth/routes.py", line 19, in login
    user = User.query.filter_by(username=form.username.data).first()
  File "/home/leewel/.local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 512, in __get__
    mapper = orm.class_mapper(type)
  File "/home/leewel/.local/lib/python2.7/site-packages/sqlalchemy/orm/base.py", line 421, in class_mapper
    mapper = _inspect_mapped_class(class_, configure=configure)
  File "/home/leewel/.local/lib/python2.7/site-packages/sqlalchemy/orm/base.py", line 400, in _inspect_mapped_class
    mapper._configure_all()
  File "/home/leewel/.local/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 1222, in _configure_all
    configure_mappers()
  File "/home/leewel/.local/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 2872, in configure_mappers
    mapper._post_configure_properties()
  File "/home/leewel/.local/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 1765, in _post_configure_properties
    prop.init()
  File "/home/leewel/.local/lib/python2.7/site-packages/sqlalchemy/orm/interfaces.py", line 184, in init
    self.do_init()
  File "/home/leewel/.local/lib/python2.7/site-packages/sqlalchemy/orm/relationships.py", line 1653, in do_init
    self._process_dependent_arguments()
  File "/home/leewel/.local/lib/python2.7/site-packages/sqlalchemy/orm/relationships.py", line 1710, in _process_dependent_arguments
    self.target = self.mapper.mapped_table
  File "/home/leewel/.local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 764, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/leewel/.local/lib/python2.7/site-packages/sqlalchemy/orm/relationships.py", line 1639, in mapper
    % (self.key, type(argument)))
ArgumentError: relationship 'notifications' expects a class or a mapper argument (received: <class 'sqlalchemy.sql.schema.Table'>)
2018-12-07 18:06:59,919 INFO: Microblog startup [in /home/leewel/Development/repos/Blog/app/__init__.py:77]
